version: '3.8'

services:
  carnetizacion-digital-api-qa:
    container_name: carnetizacion-digital-api-qa
    build:
      context: ../..        # ðŸ”¹ sube dos niveles (desde devops/qa hasta raÃ­z del proyecto)
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5101:8080"
    networks:
      - network_qa
    labels:
      - com.carnetizacion.environment=qa
    command: >
      sh -c "
        echo 'Ejecutando migraciones de Entity Framework...';
        dotnet ef database update --project ./Entity/Entity.csproj --startup-project ./Web/Web.csproj;
        echo 'Migraciones completadas. Iniciando la API...';
        dotnet ./Web/bin/Release/net8.0/Web.dll
      "

networks:
  network_qa:
    external: true
