version: '3.8'

services:
  carnetizacion-digital-api-staging:
    container_name: carnetizacion-digital-api-staging
    build:
      context: ../..
      dockerfile: Dockerfile
    image: carnetizacion-digital-api-staging
    env_file:
      - .env
    restart: always
    ports:
      - "5102:8080"
    networks:
      - network_staging
    command: >
      bash -c "
        echo 'â³ Esperando base de datos...';
        until nc -z carnetizacion-postgres-staging 5432; do
          echo 'ğŸ” AÃºn no disponible...';
          sleep 5;
        done;

        echo 'ğŸ“¦ Instalando EF Core CLI...';
        dotnet tool install --global dotnet-ef --version 8.0.0;
        export PATH=\$PATH:/root/.dotnet/tools;

        echo 'ğŸ§© Creando nueva migraciÃ³n incremental de Entity Framework...';
        TIMESTAMP=\$(date +%Y%m%d%H%M%S);
        dotnet ef migrations add AutoMigration_\$TIMESTAMP \
          --project Entity/Entity.csproj \
          --startup-project Web/Web.csproj;

        echo 'ğŸ—ï¸ Aplicando migraciones a la base de datos...';
        dotnet ef database update \
          --project Entity/Entity.csproj \
          --startup-project Web/Web.csproj;

        echo 'âœ… Nueva migraciÃ³n aplicada correctamente.';
        echo 'ğŸš€ Iniciando aplicaciÃ³n...';
        dotnet Web.dll
      "


networks:
  network_staging:
    external: true
