version: '3.8'

services:
  carnetizacion-db-migrator-staging:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    build:
      context: ../..
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - network_staging
    working_dir: /app
    volumes:
      - ../..:/app
    entrypoint: >
      bash -c "
        apt-get update && apt-get install -y netcat-openbsd;
        echo 'â³ Esperando base de datos...';
        until nc -z carnetizacion-postgres-staging 5432; do
          echo 'ğŸ” AÃºn no disponible...';
          sleep 5;
        done;

        echo 'ğŸ—ï¸ Verificando migraciones existentes...';
        export PATH=\"\$PATH:/root/.dotnet/tools\";

        MIG_COUNT=\$(dotnet ef migrations list --project Entity/Entity.csproj --startup-project Web/Web.csproj | wc -l);

        if [ \"\$MIG_COUNT\" -eq 0 ]; then
          echo 'âš™ï¸ No se encontraron migraciones. Creando una nueva...';
          TIMESTAMP=\$(date +%Y%m%d%H%M%S);
          dotnet ef migrations add AutoMigration_\$TIMESTAMP --project Entity/Entity.csproj --startup-project Web/Web.csproj;
        fi;

        echo 'ğŸš€ Aplicando migraciones...';
        dotnet ef database update --project Entity/Entity.csproj --startup-project Web/Web.csproj;

        echo 'âœ… Migraciones aplicadas correctamente.';
      "

  carnetizacion-digital-api-staging:
    container_name: carnetizacion-digital-api-staging
    image: carnetizacion-digital-api-staging
    build:
      context: ../..
      dockerfile: Dockerfile
    depends_on:
      - carnetizacion-db-migrator-staging
    env_file:
      - .env
    restart: always
    ports:
      - "5102:8080"
    networks:
      - network_staging
    command: ["dotnet", "Web.dll"]

networks:
  network_staging:
    external: true
