
services:
  carnetizacion-digital-api-staging:
    container_name: carnetizacion-digital-api-staging
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5105:8080"
    networks:
      - network_staging
    labels:
      - com.carnetizacion.environment=staging

networks:
  network_staging:
    external: true
